name: codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
    - name: Generate coverage report
      run: |
        choco install opencover.portable
        choco install dotnetcore-sdk
        OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\aiof.auth.tests\bin\Debug\netcoreapp3.1\aiof.auth.tests.dll -noshadow" -output:".\coverage.xml"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-unittests
        path_to_write_report: ./coverage/codecov_report.gz
