name: owasp-scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  owasp-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: OWASP ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.1.0
